const PostActionTypes = {
  FETCH_POSTS_START: "FETCH_POSTS_DATA",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  ADD_POST_START: "ADD_POST_START",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",
  ADD_LIKE: "ADD_LIKE",
  ADD_LIKE_ERROR: "ADD_LIKE_ERROR",
};
export default PostActionTypes;
