const UserPostsTypes={
    GET_POSTS_BY_USER_START: "GET_POSTS_BY_USER",
    GET_POSTS_BY_USER_SUCCESS: "GET_POSTS_BY_USER_SUCCESS",
    GET_POSTS_BY_USER_FAILURE: "GET_POSTS_BY_USER_FAILURE",
}
export default UserPostsTypes;